# Generated by Django 5.1.7 on 2025-07-25 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='name',
            new_name='nom',
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('score_equipe1', models.IntegerField(blank=True, null=True)),
                ('score_equipe2', models.IntegerField(blank=True, null=True)),
                ('phase', models.CharField(default='poule', max_length=20)),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe1', to='tournoi.equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe2', to='tournoi.equipe')),
            ],
        ),
    ]
