# Generated by Django 5.1.7 on 2025-07-25 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0002_rename_name_equipe_nom_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe1', to='tournoi.equipe'),
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe2', to='tournoi.equipe'),
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('POULES', 'Phases de poules'), ('QUART', 'Quart de finale'), ('DEMI', 'Demi-finale'), ('FINALE', 'Finale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_equipe1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_equipe2',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1)),
                ('equipes', models.ManyToManyField(to='tournoi.equipe')),
            ],
        ),
    ]
